name: API-Build

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Set local dependencies
        run: |
          mkdir -p $HOME/.m2
          cp  $GITHUB_WORKSPACE/.github/workflows/maven-settings.xml $HOME/.m2/settings.xml

      - name: Build with Maven
        run: mvn -B package --file pom.xml